import { StyleSheet } from 'react-native';

/** Shared chrome tokens (lists, forms, detail screens). */
export const APP_C = {
  indigo: '#4361EE',
  indigoLight: '#EEF2FF',
  green: '#059669',
  greenLight: '#d1fae5',
  amber: '#d97706',
  amberLight: '#fef3c7',
  violet: '#7c3aed',
  violetLight: '#f5f3ff',
  red: '#dc2626',
  redLight: '#fee2e2',
  bg: '#F8FAFC',
  surface: '#ffffff',
  text: '#0f172a',
  textSub: '#475569',
  textMuted: '#94a3b8',
  border: '#E2E8F0',
  divider: '#EEF2F6',
};

export const formUi = StyleSheet.create({
  screen: { flex: 1, backgroundColor: APP_C.bg },
  topbar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, gap: 10 },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: APP_C.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: APP_C.border,
  },
  topTitle: { fontSize: 18, fontWeight: '800', color: APP_C.text },
  topSub: { fontSize: 12, color: APP_C.textSub, marginTop: 1 },
  scroll: { padding: 16, gap: 14 },
  card: {
    backgroundColor: APP_C.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: APP_C.border,
    gap: 12,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: APP_C.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: APP_C.textSub, marginBottom: 6 },
  field: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
    borderWidth: 1,
    borderColor: APP_C.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: APP_C.bg,
    gap: 8,
  },
  fieldError: { borderColor: APP_C.red },
  fieldTxt: { flex: 1, fontSize: 15, color: APP_C.text },
  placeholder: { color: APP_C.textMuted },
  errorTxt: { fontSize: 12, color: APP_C.red, marginTop: 4 },
  hint: { fontSize: 12, color: APP_C.textMuted, lineHeight: 17 },
  row2: { flexDirection: 'row', gap: 10 },
  half: { flex: 1 },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: APP_C.bg,
    borderWidth: 1,
    borderColor: APP_C.border,
  },
  pillActive: { backgroundColor: APP_C.indigo, borderColor: APP_C.indigo },
  pillTxt: { fontSize: 13, fontWeight: '600', color: APP_C.textSub },
  pillTxtActive: { color: '#fff' },
  statusRow: { flexDirection: 'row', gap: 8 },
  statusBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: APP_C.border,
    alignItems: 'center',
    backgroundColor: APP_C.bg,
  },
  statusBtnActive: { borderColor: APP_C.indigo, backgroundColor: APP_C.indigoLight },
  statusTxt: { fontSize: 12, fontWeight: '600', color: APP_C.textSub },
  statusTxtActive: { color: APP_C.indigo, fontWeight: '800' },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: APP_C.surface,
    borderTopWidth: 1,
    borderTopColor: APP_C.border,
  },
  primaryBtn: {
    backgroundColor: APP_C.indigo,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  primaryTxt: { fontSize: 15, fontWeight: '700', color: '#fff' },
  btnDisabled: { opacity: 0.6 },
  dangerBtn: { alignItems: 'center', paddingVertical: 14, marginTop: 4 },
  dangerTxt: { color: APP_C.red, fontWeight: '700', fontSize: 15 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  loadingTxt: { fontSize: 14, color: APP_C.textSub, marginTop: 8 },
  banner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: APP_C.indigoLight,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#c7d2fe',
  },
  bannerTitle: { fontSize: 15, fontWeight: '800', color: APP_C.text },
  bannerSub: { fontSize: 12, color: APP_C.textSub, marginTop: 2 },
  sheetBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.45)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: APP_C.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    maxHeight: '88%',
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: APP_C.border,
    alignSelf: 'center',
    marginBottom: 14,
  },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: APP_C.text },
  sheetSub: { fontSize: 13, color: APP_C.textSub, marginTop: 4, marginBottom: 16 },
});
